/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExamId = IDL.Nat;
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'expert' : IDL.Null,
  'medium' : IDL.Null,
});
export const QuestionId = IDL.Nat;
export const Question = IDL.Record({
  'id' : QuestionId,
  'difficulty' : Difficulty,
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
  'examId' : ExamId,
  'options' : IDL.Vec(IDL.Text),
  'aiGenerated' : IDL.Bool,
});
export const OllamaGenerationResult = IDL.Variant({
  'ok' : IDL.Vec(Question),
  'err' : IDL.Text,
});
export const UserId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'candidate' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'role' : UserRole,
  'email' : IDL.Text,
  'fullname' : IDL.Text,
});
export const ExamStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'draft' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ExamPublic = IDL.Record({
  'id' : ExamId,
  'status' : ExamStatus,
  'createdAt' : Timestamp,
  'roleTitle' : IDL.Text,
  'timerMinutes' : IDL.Nat,
  'passThresholdPercent' : IDL.Nat,
});
export const SessionId = IDL.Nat;
export const DifficultyBreakdown = IDL.Record({
  'easy' : IDL.Nat,
  'hard' : IDL.Nat,
  'expert' : IDL.Nat,
  'medium' : IDL.Nat,
});
export const ProctoringEventCounts = IDL.Record({
  'noiseEvents' : IDL.Nat,
  'framesCaptured' : IDL.Nat,
  'tabSwitches' : IDL.Nat,
});
export const ExamResult = IDL.Record({
  'totalCorrect' : IDL.Nat,
  'timeTakenSecs' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'perDifficultyBreakdown' : DifficultyBreakdown,
  'passed' : IDL.Bool,
  'proctoringEventCounts' : ProctoringEventCounts,
});
export const SessionStatus = IDL.Variant({
  'autoSubmitted' : IDL.Null,
  'submitted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ExamSessionPublic = IDL.Record({
  'id' : SessionId,
  'startTime' : Timestamp,
  'status' : SessionStatus,
  'endTime' : IDL.Opt(Timestamp),
  'examId' : ExamId,
  'candidateId' : UserId,
});
export const ProctoringEventType = IDL.Variant({
  'autoSubmit' : IDL.Null,
  'tabSwitch' : IDL.Null,
  'noiseBreach' : IDL.Null,
  'cameraFrame' : IDL.Null,
});
export const EventId = IDL.Nat;
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({
    'userId' : UserId,
    'role' : UserRole,
    'sessionToken' : IDL.Text,
  }),
  'err' : IDL.Record({
    'lockedUntilSecs' : IDL.Opt(IDL.Int),
    'message' : IDL.Text,
  }),
});
export const RegistrationResult = IDL.Variant({
  'ok' : IDL.Record({ 'generatedPassword' : IDL.Text }),
  'err' : IDL.Record({ 'message' : IDL.Text }),
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func(
      [
        IDL.Text,
        ExamId,
        IDL.Text,
        Difficulty,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Bool,
      ],
      [QuestionId],
      [],
    ),
  'cleanupOldCameraFrames' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createExam' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [ExamId], []),
  'generateQuestionsViaOllama' : IDL.Func(
      [IDL.Text, ExamId, IDL.Text],
      [OllamaGenerationResult],
      [],
    ),
  'getCurrentUser' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
  'getExam' : IDL.Func([IDL.Text, ExamId], [IDL.Opt(ExamPublic)], ['query']),
  'getExamResult' : IDL.Func(
      [IDL.Text, SessionId],
      [IDL.Opt(ExamResult)],
      ['query'],
    ),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'importQuestions' : IDL.Func(
      [
        IDL.Text,
        ExamId,
        IDL.Vec(IDL.Tuple(IDL.Text, Difficulty, IDL.Vec(IDL.Text), IDL.Text)),
      ],
      [IDL.Nat],
      [],
    ),
  'listExams' : IDL.Func([IDL.Text], [IDL.Vec(ExamPublic)], ['query']),
  'listQuestions' : IDL.Func(
      [IDL.Text, ExamId],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'listSessions' : IDL.Func(
      [IDL.Text, IDL.Opt(ExamId)],
      [IDL.Vec(ExamSessionPublic)],
      ['query'],
    ),
  'logProctoringEvent' : IDL.Func(
      [IDL.Text, SessionId, ProctoringEventType, IDL.Text],
      [EventId],
      [],
    ),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [RegistrationResult], []),
  'setExamStatus' : IDL.Func([IDL.Text, ExamId, ExamStatus], [IDL.Bool], []),
  'startSession' : IDL.Func([IDL.Text, ExamId], [SessionId], []),
  'storeCameraFrame' : IDL.Func(
      [IDL.Text, SessionId, IDL.Text, IDL.Int],
      [EventId],
      [],
    ),
  'submitSession' : IDL.Func(
      [IDL.Text, SessionId, IDL.Vec(IDL.Tuple(QuestionId, IDL.Text)), IDL.Bool],
      [ExamResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExamId = IDL.Nat;
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'expert' : IDL.Null,
    'medium' : IDL.Null,
  });
  const QuestionId = IDL.Nat;
  const Question = IDL.Record({
    'id' : QuestionId,
    'difficulty' : Difficulty,
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
    'examId' : ExamId,
    'options' : IDL.Vec(IDL.Text),
    'aiGenerated' : IDL.Bool,
  });
  const OllamaGenerationResult = IDL.Variant({
    'ok' : IDL.Vec(Question),
    'err' : IDL.Text,
  });
  const UserId = IDL.Nat;
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'candidate' : IDL.Null });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'role' : UserRole,
    'email' : IDL.Text,
    'fullname' : IDL.Text,
  });
  const ExamStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ExamPublic = IDL.Record({
    'id' : ExamId,
    'status' : ExamStatus,
    'createdAt' : Timestamp,
    'roleTitle' : IDL.Text,
    'timerMinutes' : IDL.Nat,
    'passThresholdPercent' : IDL.Nat,
  });
  const SessionId = IDL.Nat;
  const DifficultyBreakdown = IDL.Record({
    'easy' : IDL.Nat,
    'hard' : IDL.Nat,
    'expert' : IDL.Nat,
    'medium' : IDL.Nat,
  });
  const ProctoringEventCounts = IDL.Record({
    'noiseEvents' : IDL.Nat,
    'framesCaptured' : IDL.Nat,
    'tabSwitches' : IDL.Nat,
  });
  const ExamResult = IDL.Record({
    'totalCorrect' : IDL.Nat,
    'timeTakenSecs' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'perDifficultyBreakdown' : DifficultyBreakdown,
    'passed' : IDL.Bool,
    'proctoringEventCounts' : ProctoringEventCounts,
  });
  const SessionStatus = IDL.Variant({
    'autoSubmitted' : IDL.Null,
    'submitted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ExamSessionPublic = IDL.Record({
    'id' : SessionId,
    'startTime' : Timestamp,
    'status' : SessionStatus,
    'endTime' : IDL.Opt(Timestamp),
    'examId' : ExamId,
    'candidateId' : UserId,
  });
  const ProctoringEventType = IDL.Variant({
    'autoSubmit' : IDL.Null,
    'tabSwitch' : IDL.Null,
    'noiseBreach' : IDL.Null,
    'cameraFrame' : IDL.Null,
  });
  const EventId = IDL.Nat;
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({
      'userId' : UserId,
      'role' : UserRole,
      'sessionToken' : IDL.Text,
    }),
    'err' : IDL.Record({
      'lockedUntilSecs' : IDL.Opt(IDL.Int),
      'message' : IDL.Text,
    }),
  });
  const RegistrationResult = IDL.Variant({
    'ok' : IDL.Record({ 'generatedPassword' : IDL.Text }),
    'err' : IDL.Record({ 'message' : IDL.Text }),
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func(
        [
          IDL.Text,
          ExamId,
          IDL.Text,
          Difficulty,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Bool,
        ],
        [QuestionId],
        [],
      ),
    'cleanupOldCameraFrames' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createExam' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [ExamId],
        [],
      ),
    'generateQuestionsViaOllama' : IDL.Func(
        [IDL.Text, ExamId, IDL.Text],
        [OllamaGenerationResult],
        [],
      ),
    'getCurrentUser' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
    'getExam' : IDL.Func([IDL.Text, ExamId], [IDL.Opt(ExamPublic)], ['query']),
    'getExamResult' : IDL.Func(
        [IDL.Text, SessionId],
        [IDL.Opt(ExamResult)],
        ['query'],
      ),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'importQuestions' : IDL.Func(
        [
          IDL.Text,
          ExamId,
          IDL.Vec(IDL.Tuple(IDL.Text, Difficulty, IDL.Vec(IDL.Text), IDL.Text)),
        ],
        [IDL.Nat],
        [],
      ),
    'listExams' : IDL.Func([IDL.Text], [IDL.Vec(ExamPublic)], ['query']),
    'listQuestions' : IDL.Func(
        [IDL.Text, ExamId],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'listSessions' : IDL.Func(
        [IDL.Text, IDL.Opt(ExamId)],
        [IDL.Vec(ExamSessionPublic)],
        ['query'],
      ),
    'logProctoringEvent' : IDL.Func(
        [IDL.Text, SessionId, ProctoringEventType, IDL.Text],
        [EventId],
        [],
      ),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [RegistrationResult], []),
    'setExamStatus' : IDL.Func([IDL.Text, ExamId, ExamStatus], [IDL.Bool], []),
    'startSession' : IDL.Func([IDL.Text, ExamId], [SessionId], []),
    'storeCameraFrame' : IDL.Func(
        [IDL.Text, SessionId, IDL.Text, IDL.Int],
        [EventId],
        [],
      ),
    'submitSession' : IDL.Func(
        [
          IDL.Text,
          SessionId,
          IDL.Vec(IDL.Tuple(QuestionId, IDL.Text)),
          IDL.Bool,
        ],
        [ExamResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };