/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'expert' : null } |
  { 'medium' : null };
export interface DifficultyBreakdown {
  'easy' : bigint,
  'hard' : bigint,
  'expert' : bigint,
  'medium' : bigint,
}
export type EventId = bigint;
export type ExamId = bigint;
export interface ExamPublic {
  'id' : ExamId,
  'status' : ExamStatus,
  'createdAt' : Timestamp,
  'roleTitle' : string,
  'timerMinutes' : bigint,
  'passThresholdPercent' : bigint,
}
export interface ExamResult {
  'totalCorrect' : bigint,
  'timeTakenSecs' : bigint,
  'totalQuestions' : bigint,
  'perDifficultyBreakdown' : DifficultyBreakdown,
  'passed' : boolean,
  'proctoringEventCounts' : ProctoringEventCounts,
}
export interface ExamSessionPublic {
  'id' : SessionId,
  'startTime' : Timestamp,
  'status' : SessionStatus,
  'endTime' : [] | [Timestamp],
  'examId' : ExamId,
  'candidateId' : UserId,
}
export type ExamStatus = { 'closed' : null } |
  { 'active' : null } |
  { 'draft' : null };
export type LoginResult = {
    'ok' : { 'userId' : UserId, 'role' : UserRole, 'sessionToken' : string }
  } |
  { 'err' : { 'lockedUntilSecs' : [] | [bigint], 'message' : string } };
export type OllamaGenerationResult = { 'ok' : Array<Question> } |
  { 'err' : string };
export interface ProctoringEventCounts {
  'noiseEvents' : bigint,
  'framesCaptured' : bigint,
  'tabSwitches' : bigint,
}
export type ProctoringEventType = { 'autoSubmit' : null } |
  { 'tabSwitch' : null } |
  { 'noiseBreach' : null } |
  { 'cameraFrame' : null };
export interface Question {
  'id' : QuestionId,
  'difficulty' : Difficulty,
  'correctAnswer' : string,
  'questionText' : string,
  'examId' : ExamId,
  'options' : Array<string>,
  'aiGenerated' : boolean,
}
export type QuestionId = bigint;
export type RegistrationResult = { 'ok' : { 'generatedPassword' : string } } |
  { 'err' : { 'message' : string } };
export type SessionId = bigint;
export type SessionStatus = { 'autoSubmitted' : null } |
  { 'submitted' : null } |
  { 'inProgress' : null };
export type Timestamp = bigint;
export type UserId = bigint;
export interface UserPublic {
  'id' : UserId,
  'role' : UserRole,
  'email' : string,
  'fullname' : string,
}
export type UserRole = { 'admin' : null } |
  { 'candidate' : null };
export interface _SERVICE {
  'addQuestion' : ActorMethod<
    [string, ExamId, string, Difficulty, Array<string>, string, boolean],
    QuestionId
  >,
  'cleanupOldCameraFrames' : ActorMethod<[string], bigint>,
  'createExam' : ActorMethod<[string, string, bigint, bigint], ExamId>,
  'generateQuestionsViaOllama' : ActorMethod<
    [string, ExamId, string],
    OllamaGenerationResult
  >,
  'getCurrentUser' : ActorMethod<[string], [] | [UserPublic]>,
  'getExam' : ActorMethod<[string, ExamId], [] | [ExamPublic]>,
  'getExamResult' : ActorMethod<[string, SessionId], [] | [ExamResult]>,
  'getUserCount' : ActorMethod<[], bigint>,
  'importQuestions' : ActorMethod<
    [string, ExamId, Array<[string, Difficulty, Array<string>, string]>],
    bigint
  >,
  'listExams' : ActorMethod<[string], Array<ExamPublic>>,
  'listQuestions' : ActorMethod<[string, ExamId], Array<Question>>,
  'listSessions' : ActorMethod<
    [string, [] | [ExamId]],
    Array<ExamSessionPublic>
  >,
  'logProctoringEvent' : ActorMethod<
    [string, SessionId, ProctoringEventType, string],
    EventId
  >,
  'login' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[string], undefined>,
  'register' : ActorMethod<[string, string], RegistrationResult>,
  'setExamStatus' : ActorMethod<[string, ExamId, ExamStatus], boolean>,
  'startSession' : ActorMethod<[string, ExamId], SessionId>,
  'storeCameraFrame' : ActorMethod<
    [string, SessionId, string, bigint],
    EventId
  >,
  'submitSession' : ActorMethod<
    [string, SessionId, Array<[QuestionId, string]>, boolean],
    ExamResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];