/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface UserPublic {
    id: UserId;
    role: UserRole;
    email: string;
    fullname: string;
}
export type EventId = bigint;
export type QuestionId = bigint;
export type SessionId = bigint;
export type RegistrationResult = {
    __kind__: "ok";
    ok: {
        generatedPassword: string;
    };
} | {
    __kind__: "err";
    err: {
        message: string;
    };
};
export interface ProctoringEventCounts {
    noiseEvents: bigint;
    framesCaptured: bigint;
    tabSwitches: bigint;
}
export type OllamaGenerationResult = {
    __kind__: "ok";
    ok: Array<Question>;
} | {
    __kind__: "err";
    err: string;
};
export interface ExamPublic {
    id: ExamId;
    status: ExamStatus;
    createdAt: Timestamp;
    roleTitle: string;
    timerMinutes: bigint;
    passThresholdPercent: bigint;
}
export type ExamId = bigint;
export type UserId = bigint;
export interface DifficultyBreakdown {
    easy: bigint;
    hard: bigint;
    expert: bigint;
    medium: bigint;
}
export interface ExamSessionPublic {
    id: SessionId;
    startTime: Timestamp;
    status: SessionStatus;
    endTime?: Timestamp;
    examId: ExamId;
    candidateId: UserId;
}
export type LoginResult = {
    __kind__: "ok";
    ok: {
        userId: UserId;
        role: UserRole;
        sessionToken: string;
    };
} | {
    __kind__: "err";
    err: {
        lockedUntilSecs?: bigint;
        message: string;
    };
};
export interface Question {
    id: QuestionId;
    difficulty: Difficulty;
    correctAnswer: string;
    questionText: string;
    examId: ExamId;
    options: Array<string>;
    aiGenerated: boolean;
}
export interface ExamResult {
    totalCorrect: bigint;
    timeTakenSecs: bigint;
    totalQuestions: bigint;
    perDifficultyBreakdown: DifficultyBreakdown;
    passed: boolean;
    proctoringEventCounts: ProctoringEventCounts;
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    expert = "expert",
    medium = "medium"
}
export enum ExamStatus {
    closed = "closed",
    active = "active",
    draft = "draft"
}
export enum ProctoringEventType {
    autoSubmit = "autoSubmit",
    tabSwitch = "tabSwitch",
    noiseBreach = "noiseBreach",
    cameraFrame = "cameraFrame"
}
export enum SessionStatus {
    autoSubmitted = "autoSubmitted",
    submitted = "submitted",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    candidate = "candidate"
}
export interface backendInterface {
    addQuestion(sessionToken: string, examId: ExamId, questionText: string, difficulty: Difficulty, options: Array<string>, correctAnswer: string, aiGenerated: boolean): Promise<QuestionId>;
    cleanupOldCameraFrames(sessionToken: string): Promise<bigint>;
    createExam(sessionToken: string, roleTitle: string, timerMinutes: bigint, passThresholdPercent: bigint): Promise<ExamId>;
    generateQuestionsViaOllama(sessionToken: string, examId: ExamId, role: string): Promise<OllamaGenerationResult>;
    getCurrentUser(sessionToken: string): Promise<UserPublic | null>;
    getExam(sessionToken: string, examId: ExamId): Promise<ExamPublic | null>;
    getExamResult(sessionToken: string, sessionId: SessionId): Promise<ExamResult | null>;
    getUserCount(): Promise<bigint>;
    importQuestions(sessionToken: string, examId: ExamId, qs: Array<[string, Difficulty, Array<string>, string]>): Promise<bigint>;
    listExams(sessionToken: string): Promise<Array<ExamPublic>>;
    listQuestions(sessionToken: string, examId: ExamId): Promise<Array<Question>>;
    listSessions(sessionToken: string, examId: ExamId | null): Promise<Array<ExamSessionPublic>>;
    logProctoringEvent(sessionToken: string, sessionId: SessionId, eventType: ProctoringEventType, metadata: string): Promise<EventId>;
    login(email: string, password: string): Promise<LoginResult>;
    logout(sessionToken: string): Promise<void>;
    register(fullname: string, email: string): Promise<RegistrationResult>;
    setExamStatus(sessionToken: string, examId: ExamId, status: ExamStatus): Promise<boolean>;
    startSession(sessionToken: string, examId: ExamId): Promise<SessionId>;
    storeCameraFrame(sessionToken: string, sessionId: SessionId, storageId: string, timestamp: bigint): Promise<EventId>;
    submitSession(sessionToken: string, sessionId: SessionId, answerList: Array<[QuestionId, string]>, autoSubmit: boolean): Promise<ExamResult>;
}
import type { Difficulty as _Difficulty, ExamId as _ExamId, ExamPublic as _ExamPublic, ExamResult as _ExamResult, ExamSessionPublic as _ExamSessionPublic, ExamStatus as _ExamStatus, LoginResult as _LoginResult, OllamaGenerationResult as _OllamaGenerationResult, ProctoringEventType as _ProctoringEventType, Question as _Question, QuestionId as _QuestionId, RegistrationResult as _RegistrationResult, SessionId as _SessionId, SessionStatus as _SessionStatus, Timestamp as _Timestamp, UserId as _UserId, UserPublic as _UserPublic, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addQuestion(arg0: string, arg1: ExamId, arg2: string, arg3: Difficulty, arg4: Array<string>, arg5: string, arg6: boolean): Promise<QuestionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1, arg2, to_candid_Difficulty_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1, arg2, to_candid_Difficulty_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async cleanupOldCameraFrames(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupOldCameraFrames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupOldCameraFrames(arg0);
            return result;
        }
    }
    async createExam(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<ExamId> {
        if (this.processError) {
            try {
                const result = await this.actor.createExam(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExam(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async generateQuestionsViaOllama(arg0: string, arg1: ExamId, arg2: string): Promise<OllamaGenerationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQuestionsViaOllama(arg0, arg1, arg2);
                return from_candid_OllamaGenerationResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQuestionsViaOllama(arg0, arg1, arg2);
            return from_candid_OllamaGenerationResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(arg0: string): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExam(arg0: string, arg1: ExamId): Promise<ExamPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExam(arg0, arg1);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExam(arg0, arg1);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamResult(arg0: string, arg1: SessionId): Promise<ExamResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamResult(arg0, arg1);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamResult(arg0, arg1);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCount();
            return result;
        }
    }
    async importQuestions(arg0: string, arg1: ExamId, arg2: Array<[string, Difficulty, Array<string>, string]>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.importQuestions(arg0, arg1, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importQuestions(arg0, arg1, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async listExams(arg0: string): Promise<Array<ExamPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExams(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExams(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuestions(arg0: string, arg1: ExamId): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestions(arg0, arg1);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestions(arg0, arg1);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSessions(arg0: string, arg1: ExamId | null): Promise<Array<ExamSessionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessions(arg0, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessions(arg0, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async logProctoringEvent(arg0: string, arg1: SessionId, arg2: ProctoringEventType, arg3: string): Promise<EventId> {
        if (this.processError) {
            try {
                const result = await this.actor.logProctoringEvent(arg0, arg1, to_candid_ProctoringEventType_n31(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logProctoringEvent(arg0, arg1, to_candid_ProctoringEventType_n31(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<RegistrationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_RegistrationResult_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_RegistrationResult_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async setExamStatus(arg0: string, arg1: ExamId, arg2: ExamStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setExamStatus(arg0, arg1, to_candid_ExamStatus_n40(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExamStatus(arg0, arg1, to_candid_ExamStatus_n40(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async startSession(arg0: string, arg1: ExamId): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0, arg1);
            return result;
        }
    }
    async storeCameraFrame(arg0: string, arg1: SessionId, arg2: string, arg3: bigint): Promise<EventId> {
        if (this.processError) {
            try {
                const result = await this.actor.storeCameraFrame(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeCameraFrame(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitSession(arg0: string, arg1: SessionId, arg2: Array<[QuestionId, string]>, arg3: boolean): Promise<ExamResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Difficulty_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ExamPublic_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamPublic): ExamPublic {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ExamSessionPublic_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamSessionPublic): ExamSessionPublic {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ExamStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamStatus): ExamStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_OllamaGenerationResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OllamaGenerationResult): OllamaGenerationResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationResult_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationResult): RegistrationResult {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExamPublic]): ExamPublic | null {
    return value.length === 0 ? null : from_candid_ExamPublic_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExamResult]): ExamResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    role: _UserRole;
    email: string;
    fullname: string;
}): {
    id: UserId;
    role: UserRole;
    email: string;
    fullname: string;
} {
    return {
        id: value.id,
        role: from_candid_UserRole_n13(_uploadFile, _downloadFile, value.role),
        email: value.email,
        fullname: value.fullname
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExamId;
    status: _ExamStatus;
    createdAt: _Timestamp;
    roleTitle: string;
    timerMinutes: bigint;
    passThresholdPercent: bigint;
}): {
    id: ExamId;
    status: ExamStatus;
    createdAt: Timestamp;
    roleTitle: string;
    timerMinutes: bigint;
    passThresholdPercent: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ExamStatus_n18(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        roleTitle: value.roleTitle,
        timerMinutes: value.timerMinutes,
        passThresholdPercent: value.passThresholdPercent
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    startTime: _Timestamp;
    status: _SessionStatus;
    endTime: [] | [_Timestamp];
    examId: _ExamId;
    candidateId: _UserId;
}): {
    id: SessionId;
    startTime: Timestamp;
    status: SessionStatus;
    endTime?: Timestamp;
    examId: ExamId;
    candidateId: UserId;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_SessionStatus_n28(_uploadFile, _downloadFile, value.status),
        endTime: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.endTime)),
        examId: value.examId,
        candidateId: value.candidateId
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    role: _UserRole;
    sessionToken: string;
}): {
    userId: UserId;
    role: UserRole;
    sessionToken: string;
} {
    return {
        userId: value.userId,
        role: from_candid_UserRole_n13(_uploadFile, _downloadFile, value.role),
        sessionToken: value.sessionToken
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lockedUntilSecs: [] | [bigint];
    message: string;
}): {
    lockedUntilSecs?: bigint;
    message: string;
} {
    return {
        lockedUntilSecs: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.lockedUntilSecs)),
        message: value.message
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    difficulty: _Difficulty;
    correctAnswer: string;
    questionText: string;
    examId: _ExamId;
    options: Array<string>;
    aiGenerated: boolean;
}): {
    id: QuestionId;
    difficulty: Difficulty;
    correctAnswer: string;
    questionText: string;
    examId: ExamId;
    options: Array<string>;
    aiGenerated: boolean;
} {
    return {
        id: value.id,
        difficulty: from_candid_Difficulty_n8(_uploadFile, _downloadFile, value.difficulty),
        correctAnswer: value.correctAnswer,
        questionText: value.questionText,
        examId: value.examId,
        options: value.options,
        aiGenerated: value.aiGenerated
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    candidate: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "candidate" in value ? UserRole.candidate : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    active: null;
} | {
    draft: null;
}): ExamStatus {
    return "closed" in value ? ExamStatus.closed : "active" in value ? ExamStatus.active : "draft" in value ? ExamStatus.draft : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    autoSubmitted: null;
} | {
    submitted: null;
} | {
    inProgress: null;
}): SessionStatus {
    return "autoSubmitted" in value ? SessionStatus.autoSubmitted : "submitted" in value ? SessionStatus.submitted : "inProgress" in value ? SessionStatus.inProgress : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        userId: _UserId;
        role: _UserRole;
        sessionToken: string;
    };
} | {
    err: {
        lockedUntilSecs: [] | [bigint];
        message: string;
    };
}): {
    __kind__: "ok";
    ok: {
        userId: UserId;
        role: UserRole;
        sessionToken: string;
    };
} | {
    __kind__: "err";
    err: {
        lockedUntilSecs?: bigint;
        message: string;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n35(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_record_n36(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        generatedPassword: string;
    };
} | {
    err: {
        message: string;
    };
}): {
    __kind__: "ok";
    ok: {
        generatedPassword: string;
    };
} | {
    __kind__: "err";
    err: {
        message: string;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Question>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Question>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    expert: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "expert" in value ? Difficulty.expert : "medium" in value ? Difficulty.medium : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExamPublic>): Array<ExamPublic> {
    return value.map((x)=>from_candid_ExamPublic_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExamSessionPublic>): Array<ExamSessionPublic> {
    return value.map((x)=>from_candid_ExamSessionPublic_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ExamStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamStatus): _ExamStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_ProctoringEventType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProctoringEventType): _ProctoringEventType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamId | null): [] | [_ExamId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_tuple_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, Difficulty, Array<string>, string]): [string, _Difficulty, Array<string>, string] {
    return [
        value[0],
        to_candid_Difficulty_n1(_uploadFile, _downloadFile, value[1]),
        value[2],
        value[3]
    ];
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    expert: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.expert ? {
        expert: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProctoringEventType): {
    autoSubmit: null;
} | {
    tabSwitch: null;
} | {
    noiseBreach: null;
} | {
    cameraFrame: null;
} {
    return value == ProctoringEventType.autoSubmit ? {
        autoSubmit: null
    } : value == ProctoringEventType.tabSwitch ? {
        tabSwitch: null
    } : value == ProctoringEventType.noiseBreach ? {
        noiseBreach: null
    } : value == ProctoringEventType.cameraFrame ? {
        cameraFrame: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamStatus): {
    closed: null;
} | {
    active: null;
} | {
    draft: null;
} {
    return value == ExamStatus.closed ? {
        closed: null
    } : value == ExamStatus.active ? {
        active: null
    } : value == ExamStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, Difficulty, Array<string>, string]>): Array<[string, _Difficulty, Array<string>, string]> {
    return value.map((x)=>to_candid_tuple_n22(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
